version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    command: "--log.level=DEBUG"
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
